const PHOTOS_ACTION_TYPES = {
    SET_IMAGES: 'photos/SET_CURRENT_SEARCHED_IMAGES',
    SET_SEARCH_PARAMETER: 'search/SET_SEARCH_PARAMETER',
    SET_LOADING: 'spinner/SET_LOADING'
};
  
export default PHOTOS_ACTION_TYPES;